language: node_js
node_js: 9
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.3
env:
  global:
  - GITHUB_REPO: blckchnd/rudex-ui
  - ORGANIZATION_REPO: blckchnd/rudex.org
  - WALLET_REPO: blckchnd/market.rudex.org
  - CXX=g++-4.8
  - secure: "deD+B8xDM7cguX+PbeOSLh30mi6gHAdlqQphP63ZSCuFbL6hQU7MMb8nmBdBpIuaG2rX5GejSqPWTKt+/MSgQNHMTvRnzG1l1JtDTEAky8ssMyxI+HWiRe7Ic+1pFR0qUBAcPVN3MgPtW3Za47v1IyDyaR/0GdSREdy2KvmwBOWMoT23ubA1QlEhFO7uOlium4gJ6trxNPwfXkNHiMzanpVFyRQljY1PNGEPRzRzyWPNvZ4Pq5yNKnFFcW+afhvsTtK8AoeMFDeKhDF2yva8U0IMCZzrSKWwCIhkhJPii7pPT2LNlpjwVKXn16dRRVKO2tImmWtMpgbJjiNTRzVC4Y30+F7XPc97SpTKfGvoaH/iSZpTT1la0gHgoeBB32y6buPKnF7M2UNwTt2eGXpg/JHyperyQ25ey9EQBk/vHNxS9M3jcfkoXneBOnwICHgrzfamHxmMsiXnNDDriyPqIY9kFGQubqEF74cvBxhPLmfxJCPyHx7BY9ioiAlcgzWqJDOp/ADLjpoh44rUCpQH26Zg0N9efOuLUhuTAa54/9rboWZLxjxEvJ5qfTe+eHMW1r2RzoMJqWOhkbMs4f/qqGY42nqWhiibdSAZzIBuPYt/m9kdQ33930dKWoIkJwqZ2Il+T3FWJtzaguuoxKKYzsok9c/6FY7MbSSPaPw+fjg="
cache:
  directories:
    - "node_modules"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - xz-utils
install:
  - npm i
script: "./build.sh"
#after_success: "./deploy.sh"
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
  body: Automated release from Travis CI with added files from AppVeyor build
  api_key:
    secure: "n+dpQi+eVJRGEEyAySYXOzIjS6ObFvGCGGdY2EhZhIMIB2U2FWIdzzhNBP4xLo2SnFgk9shLvIHHBQ5H5vyHaAICtbwQM5KLAHOXIEYzZ6q3G4/RJiSsNe7X/ZfQZ/cXZVIjOKXM2ZLQtMcV5uLZB3pwW5H2zBAYbPYjLtlIpbe4CI+RuPjVRYHks3Xf0RJifXINFwm4t9DMgV9AH0LD/N635IE1dA9eF4nr2naxSrpOVYgj1LETvZ21A9/cBAzfynB2gbva/ElWLKk07iiuWABSnyjo1dWDhCzcrQkuBGf+L5IkMcmZncN5zpscgzJQzTMYN9RYhvERqvKgc18O9QLaNcG06TlmulHwIGpbA3KNASShhckMq8WvWPQ0cPdLSIvHoql354Lz3CvCCwCdkf3+zGBgz3uA+U8p7seufSDseEFJ2On5kOO8ZsQyG0JBTVzjyQfh0EbNaxo40ZiZZTONP+C+TIS7owpVTS/2Ask7nNW7bWw9aQ61h82ub7IeCXoH2ouRRMDmikxMbRm254sEqnpCyaKO9XwApVFjgJn4mP8s7URxyVcLnMvfVmjkBJCSwmka0y1Z00oC2W4/FP3WsbIOelIQ+8Ew1M4YOoFC402H/XiQyW47Dm58UxzSZavRJMnUx5uCphxoKUUdkD+lMwB2K/4AaQFQM3GnJ9U="
  file_glob: true
  file:
    - build/binaries/*
    - build/release-checksums-*
  skip_cleanup: true
  draft: true
  on:
    repo: blckchnd/rudex-ui
    tags: true
